name: Run Hello World from py script
on: push

jobs:
  Environment_Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

  Script_Run:
    runs-on: ubuntu-latest
    needs: Environment_Setup
    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Run Python script
        run: python hellopython.py
